// Code generated by protoc-gen-go-kirito. DO NOT EDIT.
// versions:
// - protoc-gen-go-kirito v0.0.1
// source: proto/test.proto

package proto

import (
	context "context"
	application "github.com/go-kirito/pkg/application"
)

// ITestUseCase is the server API for Test service.
// for forward compatibility
type ITestUseCase interface {
	CreateTest(context.Context, *CreateTestRequest) (*CreateTestReply, error)
	UpdateTest(context.Context, *UpdateTestRequest) (*UpdateTestReply, error)
	DeleteTest(context.Context, *DeleteTestRequest) (*DeleteTestReply, error)
	GetTest(context.Context, *GetTestRequest) (*GetTestReply, error)
	ListTest(context.Context, *ListTestRequest) (*ListTestReply, error)
}

// @di di文件根据注解自动生成
func RegisterTestServer(app application.Application, srv ITestUseCase) {
	if app.HttpServer() != nil {
		RegisterTestHTTPServer(app.HttpServer(), srv)
	}
	if app.GrpcServer() != nil {
		RegisterTestGrpcServer(app.GrpcServer(), srv)
	}
}
