// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v1.0.0

package proto

import (
	context "context"
	http "github.com/go-kirito/pkg/transport/http"
	binding "github.com/go-kirito/pkg/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type TestHTTPServer interface {
	ListTest(context.Context, *ListTestRequest) (*ListTestReply, error)
}

func RegisterTestHTTPServer(s *http.Server, srv TestHTTPServer) {
	r := s.Route("/")
	r.GET("helloworld", _Test_ListTest0_HTTP_Handler(srv))
}

func _Test_ListTest0_HTTP_Handler(srv TestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/proto.Test/ListTest")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTest(ctx, req.(*ListTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTestReply)
		return ctx.Result(200, reply)
	}
}

type TestHTTPClient interface {
	ListTest(ctx context.Context, req *ListTestRequest, opts ...http.CallOption) (rsp *ListTestReply, err error)
}

type TestHTTPClientImpl struct {
	cc *http.Client
}

func NewTestHTTPClient(client *http.Client) TestHTTPClient {
	return &TestHTTPClientImpl{client}
}

func (c *TestHTTPClientImpl) ListTest(ctx context.Context, in *ListTestRequest, opts ...http.CallOption) (*ListTestReply, error) {
	var out ListTestReply
	pattern := "helloworld"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/proto.Test/ListTest"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
